language: node_js
node_js:
- 8.9
cache:
  directories:
  - node_modules
  - client/node_modules
addons:
  ssh_known_hosts: 54.206.106.116
script:
- cd client && yarn && cd ..
- yarn build
before_deploy:
- mkdir -p ~/.ssh/key
- openssl aes-256-cbc -K $encrypted_42e0c1fefb4c_key -iv $encrypted_42e0c1fefb4c_iv
  -in deploy_rsa.enc -out ~/.ssh/key/efcsydney.pem -d
- eval "$(ssh-agent -s)"
- chmod 400 ~/.ssh/key/efcsydney.pem
deploy:
  skip_cleanup: true
  provider: script
  script: yarn add dploy && yes | yarn deploy:qa
  on:
    branch: qa
after_deploy:
- ssh -i ~/.ssh/key/efcsydney.pem ec2-user@54.206.106.116 "cd /opt/efcsydney-roster; . ~/.bash_profile; nvm use 8; yarn"
